### ISSUE TITLE
pre_load needs to be updated for complete deserialization

### ISSUE THREAD

**Issue by jo-tham** [marshmallow-code/marshmallow-jsonapi#21]
@sloria @cmanallen @micheljung
I'm very much liking marshmallow jsonapi, but it feels like it is only useful for dumping data as a few significant issues have come up with deserialization. See:
#15 - data from relationship (and type) fields is not loaded
#18 - ma-jsonapi not compatible with webargs parser
#20 - no documentation for deserialization

To focus on #15 and #18; I get the impression that the underlying problem is that the ma-jsonapi schema does not use marshmallow fields for the 1st level jsonapi objects (e.g. relationships, data)

Would using [nested schemas](http://marshmallow.readthedocs.org/en/latest/nesting.html?highlight=nested#nesting-schemas) for the 1st level objects resolve these deserialization issues?

**Comment by cmanallen** [comment]
Hi @jo-tham 

I'm not part of the marshmallow team but, since I was mentioned, I can help you out in an unofficial capacity.

I don't believe nesting schemas are the correct answer.  My opinion is that the schema should be a flat structure.  It should be exactly as your model is (with obvious derivations).  You can use `pre_load` and `post_dump` decorators to structure and flatten the requests and responses as you see fit.

I ended up not using this library.  I wrote my own implementation.  It requires two very simple components:

`BaseSchema` schema:
- `pre_load` method to flatten the JSON API 1.0 request object
- `post_dump` method to structure the flat data structure into the JSON API 1.0 request object
- Hijack the _do_load hook so you can format errors according to the JSON API 1.0 specification 

`Relationship` field:
- Inherits from fields.Field
- Overload the _serializer and _deserialize methods

You're done!  Don't bother with the `type_` in the class meta.  Just create a required field with a default and a trivial amount of validation.

**Comment by jo-tham** [comment]
Thanks @cmanallen! sounds like a straight forward solution compared to trying to rejig ma-jsonapi to use nested fields.

I can deal with my application from here, but I'll leave this open in case @sloria has any comment. Perhaps you want `pre_load` extended as @cmanallen suggested to resolve this and related issues? 

It still won't resolve webargs compatibility, but maybe there's just no point in using webargs for deserializing request.json if the schema does its own validation and the data location is obvious...

**Comment by sloria** [comment]
Sorry for the delay in my response to this. 

I'll try to find time over the holidays to investigate the `pre_load` issue and add some documentation for deserialization. Thank you for you patience.

As always, PRs are always welcome (even if they are sketches).

**Comment by jo-tham** [comment]
I think #30 and a few PRs after that closes this, #15, #18, #20! Thanks for the nice work @cmanallen & @sloria for reviewing.

**Comment by sloria** [comment]
Clos
