### ISSUE TITLE
Using custom field for `id`

### ISSUE THREAD

**Issue by aalvrz** [marshmallow-code/marshmallow-jsonapi#418]
What is the correct way for using a different field to serialize the `id` field? I am dealing with SQLAlchemy objects that do not use an `id` field but rather a more verbose identifier like `post_id` for example.

I tried using `data_key` but it won't work:

```python
class MySchema(Schema):
    id = fields.String(dump_only=True, data_key="post_id")
```

The data is serialized, but no `id` field is present in the dump.

Using `Function` field works but I don't know if there is a better way...:

```python
class MySchema(Schema):
    id = fields.Function(lambda obj: str(obj.post_id), dump_only=True)
```

**Comment by Battlesheepu** [comment]
Hey @aalvrz ,

It's been some time since you've posted the issue, but I've realized I still might post an answer in case somebody else has a similar problem.

Have you tried using the 'attribute' argument instead of 'data_key'? 

```python
from marshmallow_jsonapi import Schema, fields


class MySchema(Schema):
    id = fields.Str(attribute='test')

    class Meta:
        type_ = "posts"


class ExampleObject:
    test = 42


instance = ExampleObject()

post_schema = MySchema()
print(post_schema.dump(instance))
```

The output to this snippet is 
```python
{'data': {'type': 'posts', 'id': '42'}}
```

Why this way? Take a look at the [Marshmallow Fields docs,](https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html#marshmallow.fields.Field) which is where the marshmallow-jsonapi's `fields.String()` comes from.

Since you are using another, already existing field to output it as the "id", it seems that "attribute" is a better fit here than "data_key".

**Comment by aalvrz** [comment]
@ww3pl Worked perfectly! Thanks for your help.
